[package]
name = "acme2-slim"
description = "AcmeV2 Support, based on acme-client crate by Onur Aslan"
version = "0.1.2"
authors = ["Onur Aslan <onur@onur.im>","Adam Shaw <discourse@gmail.com>"]
license = "MIT"
keywords = ["letsencrypt", "acme"]
readme = "README.md"
repository = "https://github.com/cyclopunk/acme2-slim"
edition = "2018"

[dependencies]
anyhow = "1.0"
serde = {version = "1.0", features=["derive"]}
serde_json = "1.0"
base64 = "0.13"
hyper = "0.13"
reqwest = { version = "0.10", default-features = false, features = ["rustls-tls", "json"] }
openssl = "0.10"
tokio = { version = "0.2", features = [ "time", "fs" ] }
tracing = "0.1"
tracing-futures = "0.2"

[dev-dependencies]
tokio = { version = "0.2", features = ["rt-threaded", "macros"] }
